import { z } from '@hono/zod-openapi';
import {
  CaseTypeSchema,
  DepartmentSchema,
  EvidenceVerdictSchema,
  SeveritySchema
} from './common.schema.js';

export const TicketResponseSchema = z.object({
  ticket_id: z.string().openapi({ example: 'TKT-98765' }),
  relevant_transaction_id: z.string().nullable().openapi({ example: 'TXN123456789' }),
  evidence_verdict: EvidenceVerdictSchema,
  case_type: CaseTypeSchema,
  severity: SeveritySchema,
  department: DepartmentSchema,
  agent_summary: z.string().openapi({ example: 'Customer claims a failed payment deducted funds. System log shows payment failed due to timeout.' }),
  recommended_next_action: z.string().openapi({ example: 'Initiate manual reversing of the transaction TXN123456789.' }),
  customer_reply: z.string().openapi({ example: 'Dear customer, we noticed your transaction failed but funds were deducted. We are reversing the amount now.' }),
  human_review_required: z.boolean().openapi({ example: true }),
  confidence: z.number().min(0).max(1).optional().openapi({ example: 0.95 }),
  reason_codes: z.array(z.string()).optional().openapi({ example: ['ERR_TIMEOUT', 'FUNDS_DEDUCTED_ON_FAIL'] }),
}).openapi('TicketResponse', {
  description: 'Analysis output generated by the AI agent service',
});
